### ISSUE TITLE
Question for github workflow for PR review

### ISSUE THREAD

**Issue by sunglee** [nikolovlazar/egghead-personal-blog-astro#22]
Hi,

Thanks for the great tutorial. I have a question during the lesson and I am not sure where I can ask, so I am leaving it in the issues. In [Create a GitHub Action Configuration to Automatic Deploy an Astro Blog](https://egghead.io/lessons/github-create-a-github-action-configuration-to-automatic-deploy-an-astro-blog) page at the end, you said like this:

> [8:56] If you'd also like to define a preview deployment for every PR before it gets merged, fly dot IO has already created a different action for that. To use this action, duplicate the fly dot YAML file in your GitHub workflows directory, change its trigger to pull requests instead of push and use the super fly slash fly PR review apps action in place of the last command in the deploy step.

If you duplicate `fly.yml` file, what should be the new preview workflow file name? Can it be any name like `fly_preview.yml` or should it be `fly.yml` and remove push workflow?

Thanks!

**Comment by nikolovlazar** [comment]
Hey @sunglee! The naming is up to you, so it can be anything that makes sense for you. My thought process was that `fly.yml` is the production, so you can definitely do `fly_preview.yml` or `fly_dev.yml`.
